# Generated by Django 5.0.6 on 2024-11-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_ordering',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
